version: '3.8'

services:
  # Web application service
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: webphulong-app
    
  # Nginx reverse proxy (tùy chọn)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: unless-stopped
    container_name: webphulong-nginx
    profiles:
      - with-nginx

networks:
  default:
    name: webphulong-network 