"""add category to service

Revision ID: c5a8f7d42e5c
Revises: b4fa8a5ec62c
Create Date: 2023-10-29 13:47:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a8f7d42e5c'
down_revision: Union[str, None] = 'b4fa8a5ec62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'category')
    # ### end Alembic commands ### 